spring.application.name=userManagament

spring.datasource.url=<Your databse URL >
spring.datasource.username=<UserName>
spring.datasource.password=<PassWord>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9091